App_GestionLocative_Authentification:
    path: /
    controller: App\Controller\AuthentificationController::authentification

App_GestionLocative_Accueil:
    path : /accueil
    controller : App\Controller\AccueilController::accueil