<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLJlHJEv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLJlHJEv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLJlHJEv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLJlHJEv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLJlHJEv\App_KernelDevDebugContainer([
    'container.build_hash' => 'LJlHJEv',
    'container.build_id' => '780e2a1b',
    'container.build_time' => 1586805199,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLJlHJEv');
