<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQFyPOQv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQFyPOQv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQFyPOQv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQFyPOQv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQFyPOQv\App_KernelDevDebugContainer([
    'container.build_hash' => 'QFyPOQv',
    'container.build_id' => '924c2cd7',
    'container.build_time' => 1586982981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQFyPOQv');
